# Generated by Django 2.1.7 on 2019-04-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190421_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzytkownik',
            old_name='uzytkownik',
            new_name='User',
        ),
    ]
